language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: getfire
    token:
      secure: "$SONAR_TOKEN"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
notifications:
  slack:
    secure: KmzsSbF8cjwGxGvm9oPhXunWf4KTS+idJu3yG6RtXt9Pvx53xKie7TEjs1OTTpd99vhfkeBGxlZNBLpQawqsFPH4n/EmNsqv0cuF+ATndqFpQx6bONMYOQj3VH6BWm3jTR4FV84cy5+/RrWQnw+wQlJV6mhoXqpkJ3caEXm5qCTKATX8LZRo7uG4gnthQOWmITGhIP8au4vvqYfLkycifEFqYvUP99h+/VHRMatCUjVuxreJQq2jC2G5zJ7DbDKJs9kYbdZykzm3ZVu/JqRWq8JM2z3EK3I9n2ivlvJb/QyPLu+JuaNNdEv9fW4M29YL4RIo2xl+D6V1MuLZBZhWbTWalXaL/b5TeOEpgliTI2oU4MklVDuwO0z1+lVgpF5YPI5+uIxojeNUmDCtMK+7VkOaqi12jzcYctHilvLoFOroJBtXqAAe099KCf3sgSJwktK8kOOdMzVok1u0wvTzu89qAcJltY3aLBt8kBMABaV1faskZeXtZjWEi4dVIbwrzN5JpJh7rmY5mGRKDsLe332tgKqfERhNQ7iqy7+75tx7O7RuyyqJfY0ALXd+mHm6qgm/as1DZAdDRXIMbnaI1E/88jmOBi8pKpWRlg1hzh7x7FJsRFM6UeoICYvsP3xRNVLLoVKfk1S4N/Tx5T5rFEAYVB6vZGQ2Y1FBAh4zRqw=
deploy:
  provider: heroku
  api_key:
    secure: iaoz5I2UKc1qs3EdPFoYgtxOZOBZKzXrofyt9mivwFhAQDhYzGddCRVaahx3mVw0LQ3+oa0U+NmjEo7hKtN26Zk+Jym/JlAecY3LDM60u3zj4lAdRZCf3183KFl7XgDl1zJFaT3swCiPKWTbFS9YlEd8iv9AUUFHQbQW+CfFqt7F+G8G7TveI4UnvzyjvIDsUQUN1cfpUrqhf+eJCB4fVKPaSlwdrghm0If9u3fHV56eD4KxDHTvo6aHlz1pUKrJv2dogbTx4fwtNQeTcTH7yB2DEkZa7HHxp5c9eG/MHOzncRDaQdpLnGL9PnTbH7t5myTSlOKdUs8298WktVUlG0zitxXCV8S2aFZxEyu52SsVn+FiOifyI3xPiiBFRUeiNP3LINz8gKM2inw9s1a3Uy+vCmUtnq7H+mkVfqnoMjYc7LSWmhovCKraqcLZ9i9Cbx+RArScQhTl4RFXaVff2v1noIBOpDXb6dJtXIqzXfGFZ7nOWliFBOA6RS86gUxBNa+bUA3BUKL2m3fXjF2F7J45nMk+mbG5TobwZugFNiwmTKLqvp0YonTwQHfoFcedlgtiluYf0bg4P5g/3zKeSqv3rX844rIjI0ibpF9Z6t95u0n450SZXBFNg6gjq5zh49ukvZ5PY4Tw08Cya5C+7HIrNmPXWkLTGL618OraMhA=
  app: likelihood-of-natural-disaster
  on:
    branch: master
#    repo: GetFire/likelihood-of-natural-disaster
