language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "getfire"
    token:
      secure: "$SONAR_TOKEN"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GetFire_likelihood-of-natural-disaster
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'